import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

import { InstructorSidebar } from '../../page/instructor-sidebar/sidebar';
import { InstructorDataService } from '../../services/instructor-data.service';
import { Certificate, InstructorProfile } from '../../mock-types';

@Component({
  selector: 'app-instructor-certificates',
  standalone: true,

  imports: [
    CommonModule,
    FormsModule,
    InstructorSidebar
  ],

  templateUrl: './instructor-certificates.html',
  styleUrl: './instructor-certificates.css'
})
export class InstructorCertificatesComponent
  implements OnInit {

  private readonly router = inject(Router);

  private readonly dataService =
    inject(InstructorDataService);

  /** The signed-in instructor, used for the header display. */
  protected instructor: InstructorProfile | null = null;


  /**
 * The template header still reads `data.instructor.*` from the old mock
 * store. These values now come from the database via /users/myProfile.
 */
  protected get data(): {
    instructor: {
      firstName: string;
      lastName: string;
      image: string | null;
      role: string;
    };
  } {
    return {
      instructor: {
        firstName: this.instructor?.firstName ?? '',
        lastName: this.instructor?.lastName ?? '',
        image: this.instructor?.img ?? this.defaultImage,
        role: this.instructor?.role ?? 'instructor',
      },
    };
  }


  protected readonly defaultImage =
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=85';


  // =========================================================
  // CERTIFICATES
  // =========================================================

  /**
   * Certificates are generated by the backend automatically when a student
   * completes a course (see generateCertificateForStudent), so this list is
   * read-only here.
   */
  certificates: Certificate[] = [];

  filteredCertificates: Certificate[] = [];


  // =========================================================
  // FILTERS
  // =========================================================

  searchText = '';

  selectedCourse = 'all';

  courses: string[] = [];


  // =========================================================
  // PAGE STATE
  // =========================================================

  loading = false;

  errorMessage = '';


  // =========================================================
  // INIT
  // =========================================================

  ngOnInit(): void {

    this.loadCertificates();

    // The header shows the signed-in instructor from the database.
    this.dataService.getProfile().subscribe({
      next: (profile) => (this.instructor = profile),
      error: () => {},
    });

  }


  // =========================================================
  // LOAD CERTIFICATES
  // =========================================================

  loadCertificates(): void {

    this.loading = true;

    this.errorMessage = '';

    this.dataService.getCertificates().subscribe({
      next: (certificates) => {
        this.certificates = certificates;

        // Get unique course names
        this.courses = [
          ...new Set(
            this.certificates.map(
              certificate =>
                certificate.courseName
            )
          )
        ];

        this.applyFilters();

        this.loading = false;
      },
      error: (error) => {
        console.error(
          'Certificates Error:',
          error
        );

        this.errorMessage =
          'Unable to load certificates.';

        this.loading = false;
      }
    });

  }


  // =========================================================
  // APPLY FILTERS
  // =========================================================

  applyFilters(): void {

    const search =
      this.searchText
        .toLowerCase()
        .trim();


    this.filteredCertificates =
      this.certificates.filter(
        certificate => {

          // ---------------------------------
          // SEARCH
          // ---------------------------------

          const studentName =
            certificate.studentName
              .toLowerCase();

          const courseName =
            certificate.courseName
              .toLowerCase();

          const certificateId =
            certificate.certificateId
              .toLowerCase();


          const matchesSearch =
            !search ||

            studentName.includes(search) ||

            courseName.includes(search) ||

            certificateId.includes(search);


          // ---------------------------------
          // COURSE FILTER
          // ---------------------------------

          const matchesCourse =
            this.selectedCourse === 'all' ||

            certificate.courseName ===
              this.selectedCourse;


          // ---------------------------------
          // FINAL RESULT
          // ---------------------------------

          return (
            matchesSearch &&
            matchesCourse
          );

        }
      );

  }


  // =========================================================
  // CLEAR FILTERS
  // =========================================================

  clearFilters(): void {

    this.searchText = '';

    this.selectedCourse = 'all';

    this.applyFilters();

  }


  // =========================================================
  // GET STUDENT INITIALS
  // =========================================================

  getStudentInitials(
    certificate: Certificate
  ): string {

    return certificate.studentName
      .split(' ')
      .filter(Boolean)
      .slice(0, 2)
      .map((part) => part[0]?.toUpperCase() ?? '')
      .join('');

  }


  // =========================================================
  // VIEW CERTIFICATE
  // =========================================================

  viewCertificate(
    certificate: Certificate
  ): void {
    const url = `http://localhost:3000/E-learning/certificate/verify/${encodeURIComponent(certificate.certificateId)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }


  // =========================================================
  // OPEN PROFILE
  // =========================================================

  openProfile(): void {

    this.router.navigate([
      '/instructor-profile'
    ]);

  }


  // =========================================================
  // EXPORT RECORDS
  // =========================================================

  exportRecords(): void {

    if (
      this.filteredCertificates.length === 0
    ) {

      return;

    }


    // Prepare rows — only fields that exist on the certificate schema.
    const rows =
      this.filteredCertificates.map(
        certificate => ({

          Certificate_ID:
            certificate.certificateId,

          Student:
            certificate.studentName,

          Course:
            certificate.courseName,

          Instructor:
            certificate.instructorName,

          Issued_Date:
            certificate.issueDate,

          Verification_URL:
            certificate.verificationUrl

        })
      );


    // Headers
    const headers =
      Object.keys(rows[0]);


    // CSV content
    const csv = [

      headers.join(','),

      ...rows.map(row =>

        headers
          .map(
            header =>
              `"${String(
                row[
                  header as keyof typeof row
                ]
              ).replace(
                /"/g,
                '""'
              )}"`
          )
          .join(',')

      )

    ].join('\n');


    // Create file
    const blob =
      new Blob(
        [csv],
        {
          type:
            'text/csv;charset=utf-8;'
        }
      );


    // Create URL
    const url =
      window.URL.createObjectURL(blob);


    // Create download link
    const link =
      document.createElement('a');


    link.href = url;

    link.download =
      'instructor-certificates.csv';


    // Download
    link.click();


    // Cleanup
    window.URL.revokeObjectURL(url);

  }


  // =========================================================
  // GET CERTIFICATE BY ID
  // =========================================================

  getCertificate(
    certificateId: string
  ): Certificate | undefined {

    return this.certificates.find(
      certificate =>
        certificate.certificateId === certificateId
    );

  }


  // =========================================================
  // COUNTS
  // =========================================================

  getTotalCertificates(): number {

    return this.filteredCertificates.length;

  }

}

